### ISSUE TITLE
Histogram of Data Distribution

### ISSUE THREAD

**Issue by kanitw** [vega/polestar#144]

**Comment by jdittrich** [comment]
would be interested in this – is there a way to help?

**Comment by domoritz** [comment]
We need to work out https://github.com/vega/polestar/pull/362 before we can add new features that significantly affect the code. Having said that, I think simple histograms for each field are probably fine. The most important question is how this would look. Right now we have an issue with a scrollable schema list (which could be fixed with https://github.com/vega/polestar/issues/363) so the histograms should probably be in a tooltip for now. 

I don't know how comfortable you are with js/angular/vega-lite/datalib but the best way would be if you could create a few mockups for the feature and then we can see how this would be implemented. 

Danke für die Hilfe!

**Comment by jdittrich** [comment]
I'm fine with JS in general, don't know vega and angular (yet). Im firm with mockups, tough :)
